### ISSUE TITLE
ldiar

### ISSUE THREAD

**Issue by zwk0901** [csiro-robotics/WildScenes#3]

**Comment by StephenHausler** [comment]
Hi @zwk0901, we had no plans to release any reflectivity or intensity data, although this is something we can look into. Will update soon if this is something we are able to release.

**Comment by phoenixGG** [comment]
If possible, could you provide the reflectivity information of the LiDAR? It’s quite important for studying off-road scenes. Thank you very much.

**Comment by StephenHausler** [comment]
Hi, just letting you both know we've now released the full raw LiDAR point clouds (360 degree FOV) with intensity and return number data as well. Unfortunately, we never saved the reflectivity data however it is possible to estimate the reflectivity based on the intensity plus the range (range as in distance between the sensor and the 3D point in question). 
These new point clouds are sampled at the same timestamps as the semantic labelled point clouds and can be considered the "super-set" of 3D points that include points that have no assigned label due to not being visible in the camera FOV.
The new data can be found in the same data portal location (https://data.csiro.au/collection/csiro:61541) inside the "Fullclouds" directory.
Closing this issue now, if any further questions feel free to reply or raise a new issue.
